name: Run test suite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        python: ["3.6", "3.7", "3.8", "3.9", "3.10"]
        matplotlib: ["2.2", "3.0", "3.1", "3.2", "3.3", "3.4"]
        pyqt: ["PyQt5", "PySide2"]
        include:
          - python: "3.6"
            matplotlib: "1.5"
            pyqt: PyQt5
          - python: "3.6"
            matplotlib: "2.0"
            pyqt: PyQt5
          - python: "3.6"
            matplotlib: "2.1"
            pyqt: PyQt5
          - python: "3.6"
            matplotlib: "2.1"
            pyqt: PySide2
        exclude:
          - python: "3.6"
            matplotlib: "3.4"
          - python: "3.6"
            matplotlib: "3.5"
          - python: "3.8"
            matplotlib: "2.2"
          - python: "3.9"
            matplotlib: "2.2"
          - python: "3.10"
            matplotlib: "2.2"
          - python: "3.10"
            matplotlib: "3.0"
      fail-fast: false

    env:
      MATPLOTLIB_VERSION: ${{ matrix.matplotlib }}
      PYQT: ${{ matrix.pyqt }}
      XDG_RUNTIME_DIR: "/tmp/runtime-runner"

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          sudo apt-get install -y xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0
          pip install QtPy ${PYQT} "matplotlib==${MATPLOTLIB_VERSION}.*"
      - name: Run tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: make test_long
