name: Selftests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.5", "3.6", "3.7", "3.8", "3.9", "3.10"]
        matplotlib: ["1.5", "2.0", "2.1", "2.2", "3.0", "3.1", "3.2", "3.3", "3.4"]
        pyqt: ["PyQt5", "PySide2"]
        exclude:
          - python: "3.5"
            matplotlib: "3.1"
            pyqt: "PyQt5"
          - python: "3.5"
            matplotlib: "3.1"
            pyqt: PySide2
          - python: "3.5"
            matplotlib: "3.2"
            pyqt: "PyQt5"
          - python: "3.5"
            matplotlib: "3.2"
            pyqt: "PySide2"
          - python: "3.5"
            matplotlib: "3.3"
            pyqt: "PyQt5"
          - python: "3.5"
            matplotlib: "3.3"
            pyqt: "PySide2"
          - python: "3.8"
            matplotlib: "1.5"
          - python: "3.8"
            matplotlib: "2.0"
          - python: "3.8"
            matplotlib: "2.1"
          - python: "3.8"
            matplotlib: "2.2"
          - python: "3.9"
            matplotlib: "1.5"
          - python: "3.9"
            matplotlib: "2.0"
          - python: "3.9"
            matplotlib: "2.1"
          - python: "3.9"
            matplotlib: "2.2"
          - python: "3.10"
            matplotlib: "1.5"
          - python: "3.10"
            matplotlib: "2.0"
          - python: "3.10"
            matplotlib: "2.1"
          - python: "3.10"
            matplotlib: "2.2"
      fail-fast: false

    env:
      MATPLOTLIB_VERSION: ${{ matrix.matplotlib }}
      PYQT: ${{ matrix.pyqt }}
      DISPLAY: :0

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup xvfb (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0
          # start xvfb on (default) display :0
          sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 &
      - name: Install dependencies
        run: |
          pip install mock QtPy ${PYQT} "matplotlib==${MATPLOTLIB_VERSION}.*"
      - name: Run tests
        run: make test_long
